export enum FeaturesEnum {
  CONFIG = 'config',
  USERS_STATE = 'usersState',
  CAMPAIGNLIST_STATE = "campaignListState",
  SALESCAMPAIGN_STATE = "salesCampaignState",
  INSUREDTYPES_STATE = "insuredTypesState",
  SERIES_STATE = "seriesState",
  CUSTOMERCATEGORY_STATE = "customerCategoryState",
  CUSTOMERCATEGORYREFUND_STATE = "customerCategoryRefundState",
  EVENTHISTORY_STATE = "eventHistoryState",
  DISCOUNTTPYE_STATE = "discountTypeState",
  PRESENTS_STATE = "presentsState",
  NOTIFICATIONS = 'notification',
  CANCELLATION = 'cancellation',
  AUTH = 'auth',
  HISTORY = 'history',
  SMS_CHECK_LIST = 'smsCheckList',
  Tasks = 'tasks',
}
